name: CI Build

on: pull_request

jobs:
  build:
    name: Check Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12.4,name=iPhone Xs Max']
    steps:
      - uses: actions/checkout@master
      - name: Build 
        run: |
         carthage update --platform ios
         xcodebuild -project Test.xcodeproj -scheme Test -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0'
        env:
          destination: ${{ matrix.destination }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with: 
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          file: Test-edlmavrgbadisocdjhmqzchupbri/Build/Products/Debug-iphonesimulator/Test.framework
          asset_name: kintone_ios_sdk.framework
          tag: ${{ github.ref }}
          overwrite: true
